server:
  servlet:
    context-path: /api
  error:
    include-message: always

spring:
  h2:
    console:
      enabled: true
      path: /h2
  datasource:
    driverClassName: org.h2.Driver
    url: jdbc:h2:mem:inditest;MODE=MySQL
  jpa:
    defer-datasource-initialization: true

